export const homePageQuery = `{
  "settings": *[_type == "homePageSeo"][0]{
    metadata,
    description,
    title,
    keywords,
    ogTitle,
    ogDescription,
    ogImage{
      ...,
      asset->{
        _id,
        url,
        metadata
      }
    },
    canonicalUrl,
    structuredData
  },
  "hero": *[_type == "homeHero"][0]{
    heading,
    subheading,
    images[]{
      ...,
      asset->{
        _id,
        url,
        metadata
      },
      alt
    }
  },
  "brandInfo": *[_type == "homeBrandInfo"][0]{
    main{
      heading,
      subheading
    },
    differentiators[]{
      id,
      title,
      description,
      icon
    },
    rightCard{
      heading,
      description,
      stats[]{
        id,
        value,
        label
      }
    }
  },
  "services": *[_type == "homeServices"][0]{
    heading,
    subheading,
    "rightCard": cards[]{
      title,
      subheading[],
      video{
        asset->{
          _id,
          url
        }
      }
    }
  },
  "keepYourStack": *[_type == "homeTechStack"][0]{
    heading,
    highlight,
    description,
    logos[]{
      name,
      bgColor,
      textColor,
      image{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      }
    }
  },
  "contentSection": *[_type == "homeContent"][0]{
    heading,
    subheading,
    benefits[]{
      id,
      title,
      description,
      stat,
      icon
    }
  },
  "process": *[_type == "homeProcess"][0]{
    steps[],
    content[]
  },
  "trustedBrands": *[_type == "homeTrustedBrands"][0]{
    heading,
    logos[]{
      name,
      image{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      }
    }
  },
  "testimonials": *[_type == "homeTestimonials"][0]{
    eyebrow,
    heading,
    testimonials[]{
      quote,
      author,
      position,
      number,
      image{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      }
    }
  },
  "bookACall": *[_type == "homeBookACall"][0]{
    heading,
    description,
    subDescription,
    buttonText,
    buttonLink,
    illustrationImage{
      ...,
      asset->{
        _id,
        url,
        metadata
      }
    }
  },
  "caseStudy": *[_type == "homeCaseStudy"][0]{
    heading,
    caseStudies[]{
      title,
      textColor,
      bgImages[]{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      },
      metrics[]{
        number,
        text
      },
      services[],
      isNew
    }
  },
  "apart": *[_type == "homeApart"][0]{
    heading,
    tagline,
    oursTitle,
    othersTitle,
    ours[],
    others[]
  }
}`;

export const portfolioPageQuery = `{
  "settings": *[_type == "portfolioPageSeo"][0]{
    metadata,
    description,
    title,
    keywords,
    ogTitle,
    ogDescription,
    ogImage{
      ...,
      asset->{
        _id,
        url,
        metadata
      }
    },
    canonicalUrl,
    structuredData
  },
  "hero": *[_type == "portfolioHero"][0]{
    label,
    title,
    description
  },
  "projects": *[_type == "portfolioProject"][0]{
    projects[]{
      slug{
        current
      },
      logoText,
      logo{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      },
      headline,
      image{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      },
      imageAlt,
      metrics[]{
        value,
        label
      },
      tags[],
      content
    }
  }
}`;

export const resourcesPageQuery = `{
  "settings": *[_type == "resourcesPageSeo"][0]{
    metadata,
    description,
    title,
    keywords,
    ogTitle,
    ogDescription,
    ogImage{
      ...,
      asset->{
        _id,
        url,
        metadata
      }
    },
    canonicalUrl,
    structuredData
  },
  "hero": *[_type == "resourcesHero"][0]{
    title,
    description,
    details[]
  },
  "articles": *[_type == "resourcesArticles"][0]{
    articles[]{
      slug{
        current
      },
      title,
      category,
      date,
      excerpt,
      image{
        ...,
        asset->{
          _id,
          url,
          metadata
        }
      },
      content
    }
  }
}`;

export const resourceArticleBySlugQuery = `*[_type == "resourcesArticles"][0]{
  "article": articles[slug.current == $slug][0]{
    slug{
      current
    },
    title,
    category,
    date,
    excerpt,
    image{
      ...,
      asset->{
        _id,
        url,
        metadata
      }
    },
    content
  }
}.article`;

export const resourceArticlesQuery = `*[_type == "resourcesArticles"][0]{
  articles[]{
    slug{
      current
    },
    title,
    category,
    date,
    excerpt,
    image{
      ...,
      asset->{
        _id,
        url,
        metadata
      }
    },
    content
  }
}.articles`;

export const resourcesPageContentQuery = `*[_type == "resourcesHero"][0]{
  title,
  description,
  details[]
}`;

