export const serviceFieldConfig = {
	"ai-automation": {
		title: "AI Automation",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"industries",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"ai-chatbots": {
		title: "AI Chatbots",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-receptionists": {
		title: "AI Receptionists",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"factory-automation": {
		title: "Factory Automation",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"social-media-automation": {
		title: "Social Media Automation",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"workflow-automation": {
		title: "Workflow Automation",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"erp-systems": {
		title: "Erp Systems",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"lead-follow-up-agent": {
		title: "Lead Follow UP Agent",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"customer-feedback-collector": {
		title: "Customer Feedback Collector",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"automation-blogging": {
		title: "Automation Blogging",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-content-generation-tools": {
		title: "AI Content Generation Tools",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-driven-email-marketing": {
		title: "AI Driven Email Marketing",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-website-personalisation": {
		title: "AI Website Personalisation",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-customer-segmentation": {
		title: "AI Customer Segmentation",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-lead-nurturing": {
		title: "AI Lead Nurturing",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-product-recommendations": {
		title: "AI Product Recommendations",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-for-sales": {
		title: "AI For Sales",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-survey-bots": {
		title: "AI Survey Bots",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"generative-ai": {
		title: "Generative AI",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"ai-transcription": {
		title: "AI Transcription",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	otherServices: {
		title: "OtherServices",
		sections: ["otherServices"],
	},
	"app-development": {
		title: "App Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"ios-app-development": {
		title: "Ios App Development",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"form",
			"content",
			"services",
			"process",
			"serviceCards",
			"faq",
		],
	},
	"android-app-development": {
		title: "Android App Development",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"form",
			"content",
			"services",
			"process",
			"serviceCards",
			"faq",
		],
	},
	"react-native-development": {
		title: "React Native Development",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"form",
			"content",
			"services",
			"process",
			"serviceCards",
			"faq",
		],
	},
	"flutter-development": {
		title: "Flutter Development",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"form",
			"content",
			"services",
			"process",
			"serviceCards",
			"faq",
		],
	},
	"software-development": {
		title: "Software Development",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"form",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"progressive-web-apps": {
		title: "Progressive Web Apps",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"form",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"content-marketing": {
		title: "Content Marketing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"process",
			"content",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"content-strategy": {
		title: "Content Strategy",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	copywriting: {
		title: "Copywriting",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"graphic-designing": {
		title: "Graphic Designing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"video-editing": {
		title: "Video Editing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"photo-shoot": {
		title: "Photo Shoot",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"video-shoot": {
		title: "Video Shoot",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"infographic-design": {
		title: "Infographic Design",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"website-copywriting": {
		title: "Website Copywriting",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"sales-copywriting": {
		title: "Sales Copywriting",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"logo-design": {
		title: "Logo Design",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	branding: {
		title: "Branding",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"press-release-writing": {
		title: "Press Release Writing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"ad-copywriting": {
		title: "AD Copywriting",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"email-marketing": {
		title: "Email Marketing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"pr-outreach": {
		title: "PR Outreach",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"video-content": {
		title: "Video Content",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	infographics: {
		title: "Infographics",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	whitepapers: {
		title: "Whitepapers",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"case-studies": {
		title: "Case Studies",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	ebooks: {
		title: "Ebooks",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"podcast-content": {
		title: "Podcast Content",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"services",
			"process",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"data-analytics": {
		title: "Data Analytics",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"conversion-rate-optimization": {
		title: "Conversion Rate Optimization",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"call-tracking": {
		title: "Call Tracking",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"reporting-and-dashboards": {
		title: "Reporting And Dashboards",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"google-analytics": {
		title: "Google Analytics",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"google-tag-manager": {
		title: "Google Tag Manager",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"industries",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"serviceCards",
			"faq",
		],
	},
	"hosting-it-security": {
		title: "Hosting IT Security",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"web-hosting": {
		title: "Web Hosting",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"wordpress-hosting": {
		title: "Wordpress Hosting",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"email-hosting": {
		title: "Email Hosting",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"reseller-hosting": {
		title: "Reseller Hosting",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"ecommerce-hosting": {
		title: "Ecommerce Hosting",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"dedicated-servers": {
		title: "Dedicated Servers",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"windows-virtual-servers": {
		title: "Windows Virtual Servers",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"linux-servers": {
		title: "Linux Servers",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	vps: {
		title: "Vps",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"shared-hosting-services": {
		title: "Shared Hosting Services",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"cloud-hosting-and-management": {
		title: "Cloud Hosting And Management",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"dedicated-hosting-services": {
		title: "Dedicated Hosting Services",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"aws-hosting-solutions": {
		title: "Aws Hosting Solutions",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"data-migration": {
		title: "Data Migration",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"website-security": {
		title: "Website Security",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"ssl-certificate-setup": {
		title: "Ssl Certificate Setup",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"web-application-firewall-setup": {
		title: "Web Application Firewall Setup",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"malware-removal-services": {
		title: "Malware Removal Services",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	"web-maintenance": {
		title: "Web Maintenance",
		sections: [
			"hero",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"form",
			"content",
			"services",
			"premiumCloudServices",
			"process",
			"features",
			"faq",
		],
	},
	industries: {
		title: "Industries",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	professionals: {
		title: "Professionals Marketing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"automotive-repair-servicing-marketing-agency": {
		title: "Automotive Repair Servicing Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"movers-relocation-services-marketing-agency": {
		title: "Movers Relocation Services Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"small-business-marketing-agency": {
		title: "Small Business Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"medium-business-marketing-agency": {
		title: "Medium Business Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"enterprise-business-marketing-agency": {
		title: "Enterprise Business Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"architect-marketing": {
		title: "Architect Marketing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"recruitment-agency-marketing": {
		title: "Recruitment Agency Marketing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"hr-marketing-agency": {
		title: "HR Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"it-marketing-agency": {
		title: "IT Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"wreckers-marketing-agency": {
		title: "Wreckers Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"automotive-repair-marketing-agency": {
		title: "Automotive Repair Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"construction-marketing-agency": {
		title: "Construction Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"florist-marketing-agency": {
		title: "Florist Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"daycare-marketing-agency": {
		title: "Daycare Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"mobile-repair-marketing-agency": {
		title: "Mobile Repair Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"supermarket-marketing-agency": {
		title: "Supermarket Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"window-tinting-marketing-agency": {
		title: "Window Tinting Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"fencing-marketing-agency": {
		title: "Fencing Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"movers-marketing-agency": {
		title: "Movers Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"travel-marketing-agency": {
		title: "Travel Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"auto-marketing-agency": {
		title: "Auto Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"jewellery-marketing-agency": {
		title: "Jewellery Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"cleaning-marketing-agency": {
		title: "Cleaning Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"healthcare-marketing-agency": {
		title: "Healthcare Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"dentists-marketing-agency": {
		title: "Dentists Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"dental-marketing-agency": {
		title: "Dental Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"chiropractic-marketing-agency": {
		title: "Chiropractic Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"physiotherapist-marketing-agency": {
		title: "Physiotherapist Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"veterinary-marketing-agency": {
		title: "Veterinary Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"medical-marketing-agency": {
		title: "Medical Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"tutoring-marketing-agency": {
		title: "Tutoring Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"gym-marketing-agency": {
		title: "Gym Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"salons-marketing-agency": {
		title: "Salons Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"restaurants-marketing-agency": {
		title: "Restaurants Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"ngo-marketing-agency": {
		title: "Ngo Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"saas-marketing-agency": {
		title: "Saas Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"fintech-marketing-agency": {
		title: "Fintech Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"b2b-marketing-agency": {
		title: "B2b Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"b2c-marketing-agency": {
		title: "B2c Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"automotive-marketing-agency": {
		title: "Automotive Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"car-removal-wreckers-marketing-agency": {
		title: "Car Removal Wreckers Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"plumbing-marketing-agency": {
		title: "Plumbing Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"roofing-marketing-agency": {
		title: "Roofing Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"hvac-marketing-agency": {
		title: "Hvac Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"electrical-marketing-agency": {
		title: "Electrical Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"landscaping-marketing-agency": {
		title: "Landscaping Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"pest-control-marketing-agency": {
		title: "Pest Control Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"painting-contractors-marketing-agency": {
		title: "Painting Contractors Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"flooring-contractors-agency": {
		title: "Flooring Contractors Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"garage-marketing-agency": {
		title: "Garage Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"solar-marketing-agency": {
		title: "Solar Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"appliance-repair-marketing-agency": {
		title: "Appliance Repair Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"locksmith-marketing-agency": {
		title: "Locksmith Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"towing-marketing-agency": {
		title: "Towing Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"handyman-marketing-agency": {
		title: "Handyman Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"carpenter-marketing-agency": {
		title: "Carpenter Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"cabinet-maker-marketing-agency": {
		title: "Cabinet Maker Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"tiling-marketing-agency": {
		title: "Tiling Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"flooring-marketing-agency": {
		title: "Flooring Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"marketing-agency": {
		title: "Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"services",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"paid-advertisement": {
		title: "Paid Advertisement",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"strategic",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"google-ads": {
		title: "Google Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"meta-ads": {
		title: "Meta Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"linkedin-ads": {
		title: "Linkedin Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"youtube-ads": {
		title: "Youtube Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"google-remarketing": {
		title: "Google Remarketing",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"google-shopping": {
		title: "Google Shopping",
		sections: [
			"hero",
			"form",
			"services",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"paid-social": {
		title: "Paid Social",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"instagram-ads": {
		title: "Instagram Ads",
		sections: [
			"hero",
			"form",
			"services",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"process",
			"content",
			"faq",
		],
	},
	"facebook-ads": {
		title: "Facebook Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"faq",
		],
	},
	"google-display-ads": {
		title: "Google Display Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"tiktok-ads": {
		title: "Tiktok Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"google-shopping-ads": {
		title: "Google Shopping Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"pay-per-click": {
		title: "Pay Per Click",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"bing-ads": {
		title: "Bing Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"linkedin-ads-management": {
		title: "Linkedin Ads Management",
		sections: [
			"hero",
			"form",
			"services",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"snapchat-ads": {
		title: "Snapchat Ads",
		sections: [
			"hero",
			"form",
			"services",
			"process",
			"serviceCards",
			"strategic",
			"content",
			"faq",
		],
	},
	"twitter-x-ads": {
		title: "Twitter X Ads",
		sections: [
			"hero",
			"form",
			"services",
			"serviceCards",
			"strategic",
			"process",
			"content",
			"faq",
		],
	},
	"pinterest-ads": {
		title: "Pinterest Ads",
		sections: [
			"hero",
			"form",
			"services",
			"serviceCards",
			"strategic",
			"process",
			"content",
			"faq",
		],
	},
	"real-estate-marketing-agency": {
		title: "Real Estate Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"mortgage-broker-marketing-agency": {
		title: "Mortgage Broker Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"physiotherapists-marketing-agency": {
		title: "Physiotherapists Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"coaches-marketing-agency": {
		title: "Coaches Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"law-firm-marketing-agency": {
		title: "Law Firm Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"accountant-marketing-agency": {
		title: "Accountant Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"financial-advisor-marketing-agency": {
		title: "Financial Advisor Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"insurance-broker-marketing-agency": {
		title: "Insurance Broker Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	"consulting-firm-marketing-agency": {
		title: "Consulting Firm Marketing Agency",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"premiumCloudServices",
			"content",
			"process",
			"keyBenefits",
			"features",
			"services",
			"faq",
		],
	},
	seo: {
		title: "Search Engine Optimisation",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"local-seo": {
		title: "Local Seo",
		sections: [
			"hero",
			"form",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"wordpress-seo": {
		title: "Wordpress Seo",
		sections: [
			"hero",
			"form",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"ecom-seo": {
		title: "Ecom Seo",
		sections: [
			"hero",
			"form",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"ai-seo": {
		title: "AI Seo",
		sections: [
			"hero",
			"form",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"shopify-seo": {
		title: "Shopify Seo",
		sections: [
			"hero",
			"form",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"seo-audits": {
		title: "Seo Audits",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	orm: {
		title: "Online Reputation Management",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"seo-migration": {
		title: "Seo Migration",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"small-business-seo": {
		title: "Small Business Seo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"lead-generation": {
		title: "Lead Generation",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"link-building": {
		title: "Link Building",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"international-seo": {
		title: "International Seo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"mobile-seo": {
		title: "Mobile Seo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"voice-search-optimisation": {
		title: "Voice Search Optimisation",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"video-seo": {
		title: "Video Seo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"youtube-seo": {
		title: "Youtube Seo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"seo-strategy": {
		title: "Seo Strategy",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	geo: {
		title: "Geo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	sge: {
		title: "Sge",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"app-store-optimisation": {
		title: "App Store Optimisation",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"guest-posting": {
		title: "Guest Posting",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"local-citations": {
		title: "Local Citations",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"penalty-recovery": {
		title: "Penalty Recovery",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"multilingual-seo": {
		title: "Multilingual Seo",
		sections: [
			"hero",
			"form",
			"features",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"content",
			"services",
			"faq",
			"serviceCards",
		],
	},
	"social-media-marketing": {
		title: "Social Media Marketing",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"facebook-marketing": {
		title: "Facebook Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"instagram-marketing": {
		title: "Instagram Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"linkedin-marketing": {
		title: "Linkedin Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"tiktok-marketing": {
		title: "Tiktok Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"youtube-community-marketing": {
		title: "Youtube Community Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"serviceCards",
			"content",
			"faq",
			"introParagraph",
			"keyBenefits",
			"features",
		],
	},
	"pinterest-marketing": {
		title: "Pinterest Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"x-marketing": {
		title: "X Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"snapchat-marketing": {
		title: "Snapchat Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"reddit-marketing": {
		title: "Reddit Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"influencer-marketing": {
		title: "Influencer Marketing",
		sections: [
			"services",
			"hero",
			"form",
			"painPoints",
			"introParagraph",
			"keyBenefits",
			"features",
			"serviceCards",
			"content",
			"faq",
		],
	},
	"web-development": {
		title: "Web Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"serviceCards",
			"content",
			"process",
			"keyBenefits",
			"features",
			"faq",
		],
	},
	"website-development": {
		title: "Website Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"web-app-development": {
		title: "Web App Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"ecommerce-development": {
		title: "Ecommerce Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"landing-page-development": {
		title: "Landing Page Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"front-end-development": {
		title: "Front End Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"back-end-development": {
		title: "Back End Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"serviceCards",
			"process",
			"faq",
		],
	},
	"cms-integration": {
		title: "Cms Integration",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"ui-ux-design": {
		title: "UI UX Design",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"custom-web-development": {
		title: "Custom Web Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"wix-website-development": {
		title: "Wix Website Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"react-js-website-development": {
		title: "React JS Website Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"wordpress-website-development": {
		title: "Wordpress Website Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"woocommerce-development": {
		title: "Woocommerce Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"magento-development": {
		title: "Magento Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"squarespace-development": {
		title: "Squarespace Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"custom-php-web-development": {
		title: "Custom Php Web Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"next-js-web-development": {
		title: "Next JS Web Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"angular-web-development": {
		title: "Angular Web Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"vue-js-web-development": {
		title: "Vue JS Web Development",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"speed-optimization": {
		title: "Speed Optimization",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"portfolio-websites": {
		title: "Portfolio Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"real-estate-websites": {
		title: "Real Estate Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"healthcare-websites": {
		title: "Healthcare Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"law-firm-websites": {
		title: "Law Firm Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"education-websites": {
		title: "Education Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"ngo-non-profit-websites": {
		title: "Ngo Non Profit Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"job-portal-websites": {
		title: "Job Portal Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"directory-listing-websites": {
		title: "Directory Listing Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
	"multi-vendor-marketplace-websites": {
		title: "Multi Vendor Marketplace Websites",
		sections: [
			"hero",
			"form",
			"introParagraph",
			"painPoints",
			"keyBenefits",
			"features",
			"content",
			"services",
			"process",
			"faq",
			"serviceCards",
		],
	},
} as const

export type ServiceKey = keyof typeof serviceFieldConfig
